/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.saloonsayoma.Views;

import com.sliit.saloonsayoma.Views.Weddingcar.booking;
import com.sliit.saloonsayoma.Views.Weddingcar.car;
import com.sliit.saloonsayoma.Views.Weddingcar.decoration;
import com.sliit.saloonsayoma.Views.Weddingcar.driver;
import com.sliit.saloonsayoma.Views.Weddingcar.menu;
import com.sliit.saloonsayoma.Views.Weddingcar.package1;
import com.sliit.saloonsayoma.Views.Weddingcar.search1;
import com.sliit.saloonsayoma.Views.navigation.Navigation;
//import com.sliit.saloonsayoma.Views.lasith.Credit;
//import com.sliit.saloonsayoma.Views.lasitha.Laitha;
import com.sliit.saloonsayoma.Views.purchase.MenuP;
import com.sliit.saloonsayoma.Views.purchase.Payments;
import com.sliit.saloonsayoma.Views.purchase.PurchaseOrders;
import com.sliit.saloonsayoma.Views.purchase.PurchaseReOrder;
import com.sliit.saloonsayoma.Views.purchase.SupplierRe;
//import com.sliit.saloonsayoma.Views.stock.ItemsReg;
//import com.sliit.saloonsayoma.Views.stock.RetunItem;
//import com.sliit.saloonsayoma.Views.stock.ReturnReorderItems;
//import com.sliit.saloonsayoma.Views.stock.SetStock;
import java.awt.Dimension;
import java.awt.GraphicsConfiguration;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author handeeban
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private java.awt.CardLayout layoutManager;

    public App() {
        initComponents();
        
        
        this.setExtendedState(App.MAXIMIZED_BOTH);

        LayoutManager layout = this.contentPanel.getLayout();
        if (layout instanceof java.awt.CardLayout) {
            this.layoutManager = (java.awt.CardLayout) layout;
        }
        initCompos();

    }

    Dimension getPlatformScreenSize() {

        GraphicsConfiguration gc = this.getGraphicsConfiguration();

        Rectangle bounds = gc.getBounds();

        Insets screenInsets = Toolkit.getDefaultToolkit().getScreenInsets(gc);

        Rectangle effectiveScreenArea = new Rectangle();

        effectiveScreenArea.x = bounds.x + screenInsets.left;
        effectiveScreenArea.y = bounds.y + screenInsets.top;
        effectiveScreenArea.height = (bounds.height - (screenInsets.top - screenInsets.bottom)) - 40;
        effectiveScreenArea.width = bounds.width - screenInsets.left - screenInsets.right;

        return effectiveScreenArea.getSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saloon Sayoma");

        jPanel1.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sliit/saloonsayoma/res/notify.png"))); // NOI18N
        jLabel1.setText("logged.user@saloonsha.com");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sliit/saloonsayoma/res/sayom.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        System.out.println(this.contentPanel.getLayout().getClass().getSimpleName());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

            showView("Navigation");
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void initCompos() {
        /*Sankajith*/
        this.contentPanel.add(m, "wCar");
     
        
        this.contentPanel.add(b, "booking");
        this.contentPanel.add(c, "car");
        this.contentPanel.add(d, "driver");
        this.contentPanel.add(dd, "decoration");
        this.contentPanel.add(s, "sSearch");
        this.contentPanel.add(p, "wPackage");
        this.contentPanel.add(m, "wCar");
        /**
         *
         */

        /*Ravishanka*/
        this.contentPanel.add(menu, "MenuP");
        this.contentPanel.add(pOrders, "pOrders");
        this.contentPanel.add(supplierreg, "Supplierreg");
        this.contentPanel.add(payments, "Payments");
        this.contentPanel.add(pReOrder, "pReOrder" );
        /*end*/

 /*Ashaan*/
//        this.contentPanel.add(iReg, "iReg");
        //this.contentPanel.add(rOItem, "rOItem");
       // this.contentPanel.add(rItem, "rItem");
       // this.contentPanel.add(sStock, "sStock");
        /**
         *
         */
        
        
        
        
        //lasitha
     //   this.contentPanel.add(li,"Lasitha");
     //   this.contentPanel.add(cr,"credit");

      this.contentPanel.add(new Navigation(), "Navigation");
        this.layoutManager.show(this.contentPanel, "Navigation");

    }

    /*sanka*/
    private final menu m = new menu();
    private final booking b = new booking();
    private final car c = new car();
    private final driver d = new driver();
    private final decoration dd = new decoration();
    private final search1 s = new search1();
    private final package1 p = new package1();

    /* end*/
 /*RAVIYA*/
    private final MenuP menu = new MenuP();
    private final PurchaseOrders pOrders = new PurchaseOrders();
    private final Payments payments = new Payments();
    private final PurchaseReOrder pReOrder =new PurchaseReOrder();
    private final SupplierRe supplierreg =new SupplierRe();
    /*edn*/

 /*Ashaan*/
//    private final ItemsReg iReg = new ItemsReg();
 //   private final ReturnReorderItems rOItem = new ReturnReorderItems();
  //  private final RetunItem rItem = new RetunItem();
  //  private final SetStock sStock = new SetStock();
    
    
    /*
    lasitha
    
    **/
    
  //  private final Laitha li = new Laitha();
  //  private final Credit cr = new Credit();
    /**
     * en
     *
     * @param view
     */
    public static void showView(String view) {
            App app = getInstance();
            app.layoutManager.show(app.contentPanel, view);
    }

    private static App app = null;

    
    //design  pattern
    private static App getInstance() {
        if (app == null) {
            app = new App();
        }
        return app;
    }

}
